# Build Pipeline for replayer-pwa
 
trigger:
    - main
 
pool:
    vmImage: ubuntu-latest
 
steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Install Node.js'
    # Building the package
    - script: |
          npm install
          npm test 
          npm run build
      displayName: 'npm install and build'
    # Publishing the test results
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
          testRunner: JUnit
          testResultsFiles: '**/junit.xml'
    # Publishing the build pipeline artifact (optional)
    # This honors the .artifactignore file
    - task: PublishPipelineArtifact@1
      inputs:
          targetPath: $(System.DefaultWorkingDirectory)/dist
          artifactName: replayer-pwa-distribution
    # FTP upload the build output
    # Note: This does not honor the .artifactignore file
